### ISSUE TITLE
Swerve Drive Drift

### ISSUE THREAD

**Issue by jordanbancino** [Team6090/FRC6090-2020#11]
As we established at Thursday's meeting, the swerve modules drift quite a bit. This could possibly because the new logic used to calculate relative position, but it could also be just the drift of the encoders.

If it's the latter, I found [this](http://www.revrobotics.com/content/sw/max/sw-docs/java/com/revrobotics/CANEncoder.html#setPositionConversionFactor(double)), which could possibly be used to increase the number of counts per revolution.

**Comment by jordanbancino** [comment]
I've spoken to the experts (Stryke Force and M.A.R.S) and the conclusion that we came to is that we'll need to run our on PI (D is negligible) loop on the roboRIO.

I still want to try increasing the precision of the NEO encoders, but yeah, be prepared for the possibility of us having to write a PI loop. @snyderethan

**Comment by snyderethan** [comment]
A lot of what I was reading online said most PID loops consisted of either PI or only I or only P, so that makes sense. This is going to fix the drift problem or the oscillation problem, or both?

**Comment by jordanbancino** [comment]
We won't really know until we try it, but we've come to the conclusion that we need to completely write the loop in Java. Look at one of my recent commits, I added a class I found online called MiniPID that should do what we want. We'll use it with the analog encoders. @snyderethan

**Comment by jordanbancino** [comment]
[SwerveIO](https://github.com/Team6090/SwerveIO) solves this problem. It has a PID loop, and uses the analog encoders. We've been using this for a while so I'm going to go ahead and close this.
