### ISSUE TITLE
Tune NeoSwerveModule Pivot PID Loop

### ISSUE THREAD

**Issue by jordanbancino** [Team6090/FRC6090-2020#2]
I just used the PID constants found [here](https://github.com/REVrobotics/SPARK-MAX-Examples/blob/master/Java/Position%20Closed%20Loop%20Control/src/main/java/frc/robot/Robot.java), but they aren't the best for our application because sometimes the motors will oscillate when idle and obviously this is no good.

I'm gonna be honest, I have no idea how the PID loop works, so I probably won't be able to fix this one. I can take a look at [the wikipedia page](https://en.wikipedia.org/wiki/PID_controller) to see if I can figure it out, and maybe I can play with some values, but I'd honestly rather work on the actual drive implementation for the time being, so I'd prefer if someone else can take care of this.

For those that are interested, I put the PID control settings in [NeoSwerveModule.java](https://github.com/Team6090/FRC6090-2020/blob/master/src/main/java/frc/robot/swerveio/NeoSwerveModule.java#L29) starting on line 29:

```java
pivotPid = pivotMotor.getPIDController();
pivotPid.setP(0.1);
pivotPid.setI(1e-4);
pivotPid.setD(1);
pivotPid.setIZone(0);
pivotPid.setFF(0);
```

**Comment by jordanbancino** [comment]
So if I'm understanding correctly, I think we need to increase the derivative to stabilize the loop. Because the proportional and integral parts are doing their job to get the motor to the correct angle, it's just oscillating a little bit, which, according to this diagram:

![](https://upload.wikimedia.org/wikipedia/commons/3/33/PID_Compensation_Animated.gif)

Would mean we raise K<sub>d</sub> up a little bit, right? I think this is going to be a lot of trial and error, so maybe once we figure out some of the other issues, I can mess with this a little bit.

**Comment by jordanbancino** [comment]
On second thought though, I don't think the motor is overshooting, in fact, I think the derivative value is too low. Yes, I think that's it, it's undershooting, then slowly correcting itself. Either way, I think the `D` value is what we need to tweak in the PID loop.

**Comment by snyderethan** [comment]
Do we have a way to print out the values of the desired angle versus what we're actually at with the oscillating wheels? I feel like if we could get that put out on shuffleboard then we could determine whether or not it's overshooting, undershooting, or if it's another problem that we don't suspect.

By my brief skimming of the Wikipedia page you linked to, it sounds like the oscillation itself is the encoders not properly sitting on the targeted angle. It seems like the integral and the derivative would be the way to go to fix this, and I'm leaning derivative because it makes the most sense to me and the fact that you had the same thought on it too makes me feel like I'm right. This will definitely have to be a trial and error thing, tweaking the coefficients until the wheels stop oscillating.

**Comment by jordanbancino** [comment]
@snyderethan Yes, we could easily print out the values, the desired angle is stored in the `targetAngle` variable in `Drivetrain.drive()`, and we could easily find the actual angle like so:

```java
SwerveDriveCalculator.convertToDegrees(swerveModule.getPivotMotorEncoder(), PIVOT_REVOLUTION);
```

So we can throw those variables to the console or onto the ShuffleBoard,  but I think it would actually be a lot better to just use the raw references, because those are already stored in `pivotRef` and `swerveModule.getPivotMotorEncoder()`, and comparing these would be just as easy. But yes, that's a good idea, checking the values.

----
I'm glad you have the same understanding as I do, that certainly makes me a bit more confident. But yeah, definitely will just have to try over and over again until we find something that works.

**Comment by snyderethan** [comment]
Don't know if you've already seen this, but I quote this off of the Wikipedia for the derivative factor of a PID loop:

> After overshooting, if the controller were to apply a large correction in the opposite direction and repeatedly overshoot the desired position, the output would **_oscillate_** around the setpoint in either a constant, growing, or decaying sinusoid.

**Comment by jordanbancino** [comment]
@snyderethan Yup, I saw I that. It makes perfect sense, that's why we have to tune it. Thanks for pointing that out!

**Comment by jordanbancino** [comment]
According to my tests, [SwerveIO](https://github.com/Team6090/SwerveIO) solves this problem via `MK2Module`s.
