### ISSUE TITLE
Separate SwerveIO

### ISSUE THREAD

**Issue by jordanbancino** [Team6090/FRC6090-2020#4]
The SwerveIO package should be separated into it's own Gradle project that we can include as a submodule. I want this to be generic enough to be used in other projects if necessary.

**Comment by snyderethan** [comment]
I'll work on this if you haven't been already, I've been reading up on it and it seems simple enough.

**Comment by jordanbancino** [comment]
@snyderethan Go for it! You'll need to make sure you depend on WPILib though, as well as the RevRobotics API.

To make SwerveIO an independent project, you're going to want to add functionality to the `AbstractSwerveModule` that allows you to control ramp rates and PID controllers. Just add some abstract methods to do it, and make sure you implement them in `NeoSwerveModule`. Do that before you separate it, so we can review your changes via a pull request.

**Comment by snyderethan** [comment]
Never mind, doesn't seem simple enough. I'll still play with it though, we'll see how far I can get.

**Comment by jordanbancino** [comment]
@snyderethan Pfft, you'll be fine. Just look at [`AbstractSwerveModule.java`](https://github.com/Team6090/FRC6090-2020/blob/master/src/main/java/frc/robot/swerveio/AbstractSwerveModule.java) and see how I did it, and add methods that you see appropriate for controlling the ramp rates and PID controller. WPI's `SpeedController` API can inspire you, for instance `setOpenLoopRampRate()` would be good inspiration for `setPivotOpenLoopRampRate()` and `setDriveOpenLoopRampRate()`, etc.

**Comment by jordanbancino** [comment]
@snyderethan SwerveIO ("Swerve - ee - oh") is now it's own independent project! Find it [here](https://github.com/Team6090/SwerveIO). This does make some breaking API changes, and also implements exactly what we're doing in our drivetrain, so we'll have some work to do integrating it into this project. That should be are focus now. I'll try to see if I can publish it, but otherwise we can add it as a source dependency or just a submodule.

**Comment by jordanbancino** [comment]
See #14
